#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : SVT-AV1
Version  : 0.7.0
Release  : 3
URL      : https://github.com/OpenVisualCloud/SVT-AV1/archive/v0.7.0.tar.gz
Source0  : https://github.com/OpenVisualCloud/SVT-AV1/archive/v0.7.0.tar.gz
Summary  : AV1-compliant encoder library core.
Group    : Development/Tools
License  : BSD-2-Clause-Patent BSD-3-Clause
Requires: SVT-AV1-bin = %{version}-%{release}
Requires: SVT-AV1-lib = %{version}-%{release}
Requires: SVT-AV1-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-meson
BuildRequires : glibc-dev
BuildRequires : nasm-bin
BuildRequires : pkg-config
BuildRequires : pkgconfig(gstreamer-1.0)
BuildRequires : pkgconfig(gstreamer-base-1.0)
BuildRequires : pkgconfig(gstreamer-video-1.0)
BuildRequires : python3

%description
# Scalable Video Technology for AV1 Encoder (SVT-AV1 Encoder)
[![AppVeyor Build Status](https://ci.appveyor.com/api/projects/status/github/OpenVisualCloud/SVT-AV1?branch=master&svg=true)](https://ci.appveyor.com/project/OpenVisualCloud/SVT-AV1)
[![Travis Build Status](https://travis-ci.com/OpenVisualCloud/SVT-AV1.svg?branch=master)](https://travis-ci.com/OpenVisualCloud/SVT-AV1)
[![Coverage Status](https://coveralls.io/repos/github/OpenVisualCloud/SVT-AV1/badge.svg?branch=master)](https://coveralls.io/github/OpenVisualCloud/SVT-AV1?branch=master)

%package bin
Summary: bin components for the SVT-AV1 package.
Group: Binaries
Requires: SVT-AV1-license = %{version}-%{release}

%description bin
bin components for the SVT-AV1 package.


%package dev
Summary: dev components for the SVT-AV1 package.
Group: Development
Requires: SVT-AV1-lib = %{version}-%{release}
Requires: SVT-AV1-bin = %{version}-%{release}
Provides: SVT-AV1-devel = %{version}-%{release}
Requires: SVT-AV1 = %{version}-%{release}

%description dev
dev components for the SVT-AV1 package.


%package lib
Summary: lib components for the SVT-AV1 package.
Group: Libraries
Requires: SVT-AV1-license = %{version}-%{release}

%description lib
lib components for the SVT-AV1 package.


%package license
Summary: license components for the SVT-AV1 package.
Group: Default

%description license
license components for the SVT-AV1 package.


%prep
%setup -q -n SVT-AV1-0.7.0
cd %{_builddir}/SVT-AV1-0.7.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604709586
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1604709586
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/SVT-AV1
cp %{_builddir}/SVT-AV1-0.7.0/LICENSE.md %{buildroot}/usr/share/package-licenses/SVT-AV1/f50c4c202ba0a7b1c89c97ccc7ee168151260d28
cp %{_builddir}/SVT-AV1-0.7.0/third_party/googletest/LICENSE %{buildroot}/usr/share/package-licenses/SVT-AV1/5a2314153eadadc69258a9429104cd11804ea304
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/SvtAv1DecApp
/usr/bin/SvtAv1EncApp

%files dev
%defattr(-,root,root,-)
/usr/include/svt-av1/EbSvtAv1.h
/usr/include/svt-av1/EbSvtAv1Dec.h
/usr/include/svt-av1/EbSvtAv1Enc.h
/usr/include/svt-av1/EbSvtAv1ErrorCodes.h
/usr/include/svt-av1/EbSvtAv1ExtFrameBuf.h
/usr/include/svt-av1/EbSvtAv1Formats.h
/usr/lib64/libSvtAv1Dec.so
/usr/lib64/libSvtAv1Enc.so
/usr/lib64/pkgconfig/SvtAv1Dec.pc
/usr/lib64/pkgconfig/SvtAv1Enc.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libSvtAv1Dec.so.0
/usr/lib64/libSvtAv1Dec.so.0.7.0
/usr/lib64/libSvtAv1Enc.so.0
/usr/lib64/libSvtAv1Enc.so.0.7.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/SVT-AV1/5a2314153eadadc69258a9429104cd11804ea304
/usr/share/package-licenses/SVT-AV1/f50c4c202ba0a7b1c89c97ccc7ee168151260d28
